### ISSUE TITLE
Errors on my A9G

### ISSUE THREAD

**Issue by Faz95210** [rpetteruti/A9GTracker#1]
Hello,

Sorry to bother you with those question, but it's been bugging me for a while,

I've been trying to use your code to work with my Maduino A9G(firmware : V02.02.20180825R), And I've encountered some issue.
I tried to use your code because it seems like a complete source to do what I'm trying to do, but I've encountered some errors. First my A9G is on a Arduino Zero but I've easily been able to alter you for that. Some of the errors I've had are with the AT+LOCATION=2 command, with give me a "GPS NOT FIX NOW" and every HTTP requests and mttq returns a error 400.

Have you ever had those error? Which version of the A9G firmware are you on?

**Comment by rpetteruti** [comment]
Hi,
The ‘gps not fix now’ message means that it cannot get enough satellites in order to get a fix, try in a more open area. I never got the second error but that error is from the server not from the A9G can you check if you ‘see’ the call from the server side? 
I suggest to use the http call because the MQTT part is less reliable.
My firmware version is the same as yours.

Regards,
Raffaele

**Comment by Faz95210** [comment]
Hi,

Indeed, I've put my A9G out of my window and I've been able to receive the location.

Thank you so much 🙏

**Comment by ayazurrehman786** [comment]
Do you have the A9G code using library.
